#!/usr/bin/env python3
"""Generate gallery prop metadata from public Rust fields; Default is evaluated by Rust.
The scanner reads named public structs and aliases, not Markdown tables. No dependencies.
"""
from pathlib import Path
import re, sys

ROOT = Path(__file__).resolve().parents[1]
def quoted(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '') + '"'
def block_body(source, start):
    opening = source.index('{', start); depth = 1; end = opening + 1
    while depth:
        if source[end] == '{': depth += 1
        if source[end] == '}': depth -= 1
        end += 1
    return source[opening + 1:end - 1]
def fields(path):
    source = path.read_text()
    forwarded = re.search(r'pub use super::(\w+)::\{[^}]*\bProps\b', source)
    if forwarded: return fields(path.with_name(forwarded[1] + '.rs'))
    name = 'Props'
    alias = re.search(r'pub (?:use|type) (\w+) as Props', source)
    if alias: name = alias[1]
    match = re.search(r'(?m)^pub struct ' + name + r'\b', source)
    if not match:
        # A public type alias uses the opposite ordering.
        alias = re.search(r'pub type Props\s*=\s*(\w+)', source)
        if alias: match = re.search(r'(?m)^pub struct ' + alias[1] + r'\b', source)
    if not match:
        render = re.search(r'pub fn render\(props: (\w+)', source)
        if render:
            name = render[1]; match = re.search(r'(?m)^pub struct ' + name + r'\b', source)
    if not match:
        if path.stem == 'typography': return None, [], False
        raise ValueError(f'No Props struct or alias in {path}')
    body = block_body(source, match.start())
    result = []; previous = 0
    for field in re.finditer(r'(?m)^\s*pub (\w+)\s*:', body):
        start = field.end(); end = start; depth = 0
        while end < len(body):
            char = body[end]
            if char in '<([': depth += 1
            if char in '>)]' and not (char == '>' and body[end - 1] == '-'): depth -= 1
            if char == ',' and depth == 0: break
            end += 1
        ty = ' '.join(body[start:end].split())
        docs = ' '.join(line.strip()[3:].strip() for line in body[previous:field.start()].splitlines() if line.strip().startswith('///'))
        result.append((field[1], ty, docs))
        previous = end + 1
    assert result, path
    attributes = source[:match.start()].rsplit('\n\n', 1)[-1]
    has_default = bool(re.search(r'impl\s+Default\s+for\s+' + name + r'\b', source) or re.search(r'#\[derive\([^]]*\bDefault\b', attributes))
    return name, result, has_default

def registry(path, name):
    text = path.read_text().split('pub const ' + name + ':')[1].split('];')[0]
    return re.findall(r'"([a-z_-]+)"', text)

component_names = registry(ROOT / 'src/showcase/mod.rs', 'COMPONENT_NAMES')
block_names = registry(ROOT / 'src/blocks/mod.rs', 'BLOCK_NAMES')
block_path = lambda slug: slug.replace('-', '/', 1).replace('-', '_') if slug not in ['action-row','attention-banner'] else slug.replace('-', '_')
rows = []
for group, names in [('primitives', component_names), ('blocks', block_names)]:
    for name in names:
        module = name if group == 'primitives' else block_path(name)
        path = ROOT / f'src/{group}/{module}.rs'
        props_name, props_fields, has_default = fields(path)
        rows.append((name, group == 'blocks', group + '::' + module.replace('/', '::'), props_fields, props_name, has_default))

out = '''// @generated by python3 examples/generate-props.py; do not edit by hand.
// Fields/types/docs come from Rust source. Default values come from Props::default().
use maud::{html, Markup};
struct Prop { name: &'static str, ty: &'static str, default: String, description: &'static str }
fn table(fields: Vec<Prop>) -> Markup {
    html! { div class="mui-docs__scroll" { table class="mui-props-table" data-generated="rust-props" {
        thead { tr { th { "Prop" } th { "Type" } th { "Default" } th { "Description" } } }
        tbody { @for field in fields { tr {
            td data-label="Prop" { code { (field.name) } }
            td data-label="Type" { code { (field.ty) } }
            td data-label="Default" { code { (field.default) } }
            td data-label="Description" { (field.description) }
        } } }
    } } }
}
pub fn render(name: &str, block: bool) -> Option<Markup> {
    Some(match (block, name) {
'''
for name, block, module, props, props_name, has_default in rows:
    if props_name is None:
        out += f'        ({str(block).lower()}, {quoted(name)}) => html! {{ p data-generated="rust-props" {{ "This module uses typed helper functions instead of a Props struct. See Examples for the function API." }} }},\n'
        continue
    out += f'        ({str(block).lower()}, {quoted(name)}) => {{\n'
    if has_default: out += f'            let props = crate::{module}::{props_name}::default();\n'
    out += '            table(vec![\n'
    for field, ty, description in props:
        default = f'format!("{{:?}}", props.{field})' if has_default else '"No struct Default; supply explicitly".into()'
        out += f'                Prop {{ name: {quoted(field)}, ty: {quoted(ty)}, default: {default}, description: {quoted(description)} }},\n'
    out += '            ])\n        },\n'
out += '        _ => return None,\n    })\n}\n'
path = ROOT / 'src/showcase/generated_props.rs'
if '--check' in sys.argv:
    assert path.read_text() == out, 'Generated Props metadata is stale; run python3 examples/generate-props.py'
    print(f'Verified generated Props: {len(rows)} APIs, {sum(len(row[3]) for row in rows)} fields.')
else:
    path.write_text(out)
    print(f'Generated Props: {len(rows)} APIs, {sum(len(row[3]) for row in rows)} fields.')
