#!/usr/bin/env python3
"""One registry for the public brand contract, CSS presets and runtime data."""
from pathlib import Path
from urllib.parse import quote
import json, sys
root = Path(__file__).resolve().parents[1]
data = json.loads((root/'static/brands/brands.json').read_text())
def expand(value):
    if not value.startswith('@'): return value
    svg = (root/'static/brands'/value[1:]).read_text().strip()
    return 'url("data:image/svg+xml,' + quote(svg, safe='') + '")'
for token in data['tokens']: token['default'] = expand(token['default'])
for brand in data['presets']: brand['values'] = [expand(v) for v in brand['values']]
q = lambda value: json.dumps(value, ensure_ascii=False)
rust = '// @generated by examples/generate-brands.py; edit static/brands/brands.json.\n'
rust += '#[derive(Clone, Copy, Debug)]\npub struct Token { pub name: &\'static str, pub label: &\'static str, pub kind: &\'static str, pub default: &\'static str }\n'
rust += '#[derive(Clone, Copy, Debug)]\npub struct Brand { pub key: &\'static str, pub label: &\'static str, pub wordmark: &\'static str, pub tagline: &\'static str, pub values: &\'static [&\'static str] }\n'
rust += 'pub const TOKENS: &[Token] = &[\n' + ''.join('    Token { '+', '.join(f'{k}: {q(t[k])}' for k in ['name','label','kind','default'])+' },\n' for t in data['tokens']) + '];\n'
rust += 'pub const BRANDS: &[Brand] = &[\n' + ''.join('    Brand { '+', '.join(f'{k}: {q(b[k])}' for k in ['key','label','wordmark','tagline'])+', values: &['+', '.join(q(v) for v in b['values'])+'] },\n' for b in data['presets']) + '];\n'
css = '/* @generated brand presets; all nine tokens, no extra contract. */\n'
for b in data['presets']:
    css += f'[data-brand="{b["key"]}"] {{\n' + ''.join(f'  {t["name"]}: {v};\n' for t,v in zip(data['tokens'],b['values'])) + '}\n'
js = '// @generated brand contract and examples.\nwindow.MaudUI.brandData = '+json.dumps(data, ensure_ascii=False, separators=(',', ':'))+';\n'
outputs = {'src/brand.rs':rust,'static/styles/brand-presets.css':css,'static/behaviors/brand_data.js':js}
for name, content in outputs.items():
    path=root/name
    if '--check' in sys.argv:
        if not path.exists() or path.read_text()!=content: raise SystemExit(f'Stale brand output: {name}')
    else: path.write_text(content)
print(('Verified' if '--check' in sys.argv else 'Generated')+' brand contract: 9 tokens, 3 presets, Rust/CSS/runtime data agree.')
