// @generated by examples/generate-brands.py; edit static/brands/brands.json.
#[derive(Clone, Copy, Debug)]
pub struct Token { pub name: &'static str, pub label: &'static str, pub kind: &'static str, pub default: &'static str }
#[derive(Clone, Copy, Debug)]
pub struct Brand { pub key: &'static str, pub label: &'static str, pub wordmark: &'static str, pub tagline: &'static str, pub values: &'static [&'static str] }
pub const TOKENS: &[Token] = &[
    Token { name: "--mui-brand-accent", label: "Accent", kind: "color", default: "#285bc5" },
    Token { name: "--mui-brand-accent-ink", label: "Text on accent", kind: "color", default: "#ffffff" },
    Token { name: "--mui-brand-font-heading", label: "Heading font", kind: "text", default: "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif" },
    Token { name: "--mui-brand-font-body", label: "Body font", kind: "text", default: "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif" },
    Token { name: "--mui-brand-radius", label: "Corner radius", kind: "text", default: "0.375rem" },
    Token { name: "--mui-brand-density", label: "Density", kind: "density", default: "1" },
    Token { name: "--mui-brand-logo-mask", label: "Logo mask (CSS url)", kind: "text", default: "url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20d%3D%22M16%203%203%2010v3h26v-3ZM5%2016h4v10H5Zm9%200h4v10h-4Zm9%200h4v10h-4ZM3%2028h26v3H3Z%22%2F%3E%3C%2Fsvg%3E\")" },
    Token { name: "--mui-brand-logo-size", label: "Logo size", kind: "text", default: "2rem" },
    Token { name: "--mui-brand-logo-radius", label: "Logo corner radius", kind: "text", default: "0" },
];
pub const BRANDS: &[Brand] = &[
    Brand { key: "lodge", label: "Lodge", wordmark: "Garden House", tagline: "Independent hospitality", values: &["#466752", "#ffffff", "Georgia, serif", "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "0.5rem", "1", "url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20d%3D%22m16%203%2011%2012h-6l7%209H18v5h-4v-5H4l7-9H5Z%22%2F%3E%3C%2Fsvg%3E\")", "2rem", "0"] },
    Brand { key: "bank", label: "Bank", wordmark: "Northline", tagline: "Business banking", values: &["#24428c", "#ffffff", "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "0.25rem", "0", "url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20d%3D%22M16%203%203%2010v3h26v-3ZM5%2016h4v10H5Zm9%200h4v10h-4Zm9%200h4v10h-4ZM3%2028h26v3H3Z%22%2F%3E%3C%2Fsvg%3E\")", "1.75rem", "0"] },
    Brand { key: "clinic", label: "Clinic", wordmark: "Commonwell", tagline: "Care for your community", values: &["#076b67", "#ffffff", "\"Trebuchet MS\", system-ui, sans-serif", "\"Inter Variable\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", system-ui, sans-serif", "0.75rem", "2", "url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20d%3D%22M12%203h8v9h9v8h-9v9h-8v-9H3v-8h9Z%22%2F%3E%3C%2Fsvg%3E\")", "2rem", "0.25rem"] },
];
